create table "public"."departments"
(
  "id"         bigint generated by default as identity not null,
  "created_at" timestamp with time zone                not null default now(),
  "updated_at" timestamp with time zone                not null default now(),
  "numer"      smallint                                not null,
  "name"       text                                    not null
);


alter table "public"."departments"
  enable row level security;

CREATE UNIQUE INDEX departments_pkey ON public.departments USING btree (id);

alter table "public"."departments"
  add constraint "departments_pkey" PRIMARY KEY using index "departments_pkey";

grant delete on table "public"."departments" to "anon";

grant insert on table "public"."departments" to "anon";

grant references on table "public"."departments" to "anon";

grant select on table "public"."departments" to "anon";

grant trigger on table "public"."departments" to "anon";

grant truncate on table "public"."departments" to "anon";

grant update on table "public"."departments" to "anon";

grant delete on table "public"."departments" to "authenticated";

grant insert on table "public"."departments" to "authenticated";

grant references on table "public"."departments" to "authenticated";

grant select on table "public"."departments" to "authenticated";

grant trigger on table "public"."departments" to "authenticated";

grant truncate on table "public"."departments" to "authenticated";

grant update on table "public"."departments" to "authenticated";

grant delete on table "public"."departments" to "service_role";

grant insert on table "public"."departments" to "service_role";

grant references on table "public"."departments" to "service_role";

grant select on table "public"."departments" to "service_role";

grant trigger on table "public"."departments" to "service_role";

grant truncate on table "public"."departments" to "service_role";

grant update on table "public"."departments" to "service_role";


