create table "public"."student_informations"
(
  "user_id"         bigint generated by default as identity not null,
  "created_at"      timestamp with time zone                not null default now(),
  "study_institute" text                                    not null,
  "study_level"     text                                    not null,
  "study_label"     text                                    not null,
  "description"     text,
  "picture_path"    text,
  "skills"          text[]                                  not null default '{}'::text[],
  "phone_number"    text
);


alter table "public"."student_informations"
  enable row level security;

CREATE UNIQUE INDEX student_informations_pkey ON public.student_informations USING btree (user_id);

CREATE UNIQUE INDEX student_informations_user_id_key ON public.student_informations USING btree (user_id);

alter table "public"."student_informations"
  add constraint "student_informations_pkey" PRIMARY KEY using index "student_informations_pkey";

alter table "public"."student_informations"
  add constraint "student_informations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES user_profiles (id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."student_informations"
  validate constraint "student_informations_user_id_fkey";

alter table "public"."student_informations"
  add constraint "student_informations_user_id_key" UNIQUE using index "student_informations_user_id_key";

grant delete on table "public"."student_informations" to "anon";

grant insert on table "public"."student_informations" to "anon";

grant references on table "public"."student_informations" to "anon";

grant select on table "public"."student_informations" to "anon";

grant trigger on table "public"."student_informations" to "anon";

grant truncate on table "public"."student_informations" to "anon";

grant update on table "public"."student_informations" to "anon";

grant delete on table "public"."student_informations" to "authenticated";

grant insert on table "public"."student_informations" to "authenticated";

grant references on table "public"."student_informations" to "authenticated";

grant select on table "public"."student_informations" to "authenticated";

grant trigger on table "public"."student_informations" to "authenticated";

grant truncate on table "public"."student_informations" to "authenticated";

grant update on table "public"."student_informations" to "authenticated";

grant delete on table "public"."student_informations" to "service_role";

grant insert on table "public"."student_informations" to "service_role";

grant references on table "public"."student_informations" to "service_role";

grant select on table "public"."student_informations" to "service_role";

grant trigger on table "public"."student_informations" to "service_role";

grant truncate on table "public"."student_informations" to "service_role";

grant update on table "public"."student_informations" to "service_role";


