create table "public"."sapristi_informations"
(
  "created_at"        timestamp with time zone                not null default now(),
  "updated_at"        timestamp with time zone                not null default now(),
  "user_profile_id"   bigint generated by default as identity not null,
  "external_activity" bigint                                  not null,
  "cleaning_help"     boolean                                 not null,
  "banned_places"     text                                    not null,
  "banned_illnesses"  text                                    not null
);


alter table "public"."sapristi_informations"
  enable row level security;

CREATE UNIQUE INDEX sapristi_informations_pkey ON public.sapristi_informations USING btree (user_profile_id);

CREATE UNIQUE INDEX sapristi_informations_user_profile_id_key ON public.sapristi_informations USING btree (user_profile_id);

alter table "public"."sapristi_informations"
  add constraint "sapristi_informations_pkey" PRIMARY KEY using index "sapristi_informations_pkey";

alter table "public"."sapristi_informations"
  add constraint "sapristi_informations_user_profile_id_fkey" FOREIGN KEY (user_profile_id) REFERENCES user_profiles (id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."sapristi_informations"
  validate constraint "sapristi_informations_user_profile_id_fkey";

alter table "public"."sapristi_informations"
  add constraint "sapristi_informations_user_profile_id_key" UNIQUE using index "sapristi_informations_user_profile_id_key";

grant delete on table "public"."sapristi_informations" to "anon";

grant insert on table "public"."sapristi_informations" to "anon";

grant references on table "public"."sapristi_informations" to "anon";

grant select on table "public"."sapristi_informations" to "anon";

grant trigger on table "public"."sapristi_informations" to "anon";

grant truncate on table "public"."sapristi_informations" to "anon";

grant update on table "public"."sapristi_informations" to "anon";

grant delete on table "public"."sapristi_informations" to "authenticated";

grant insert on table "public"."sapristi_informations" to "authenticated";

grant references on table "public"."sapristi_informations" to "authenticated";

grant select on table "public"."sapristi_informations" to "authenticated";

grant trigger on table "public"."sapristi_informations" to "authenticated";

grant truncate on table "public"."sapristi_informations" to "authenticated";

grant update on table "public"."sapristi_informations" to "authenticated";

grant delete on table "public"."sapristi_informations" to "service_role";

grant insert on table "public"."sapristi_informations" to "service_role";

grant references on table "public"."sapristi_informations" to "service_role";

grant select on table "public"."sapristi_informations" to "service_role";

grant trigger on table "public"."sapristi_informations" to "service_role";

grant truncate on table "public"."sapristi_informations" to "service_role";

grant update on table "public"."sapristi_informations" to "service_role";
