name: Deploy to Firebase Hosting
'on':
  workflow_call:
jobs:
  firebase_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Replace values in environment.ts
        run: |
          sed -i "s@SUPABASE_URL@${{ secrets.SUPABASE_URL }}@" ./src/environments/environment.ts
          sed -i "s@SUPABASE_KEY@${{ secrets.SUPABASE_KEY }}@" ./src/environments/environment.ts

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ETUPRO_8E99F }}'
          channelId: live
          projectId: etupro-8e99f
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
