name: Deploy to Firebase Hosting
'on':
  workflow_call:
jobs:
  firebase_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Replace values in environment.ts
        run: |
         sed -i "s/API_KEY: ''/API_KEY: '${{ secrets.FIREBASE_API_KEY }}'/" ./src/environments/environment.ts
         sed -i "s/AUTH_DOMAIN: ''/AUTH_DOMAIN: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'/" ./src/environments/environment.ts
         sed -i "s/PROJECT_ID: ''/PROJECT_ID: '${{ secrets.FIREBASE_PROJECT_ID }}'/" ./src/environments/environment.ts
         sed -i "s/STORAGE_BUCKET: ''/STORAGE_BUCKET: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'/" ./src/environments/environment.ts
         sed -i "s/MESSAGING_SENDER_ID: ''/MESSAGING_SENDER_ID: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'/" ./src/environments/environment.ts
         sed -i "s/APP_ID: ''/APP_ID: '${{ secrets.FIREBASE_APP_ID }}'/" ./src/environments/environment.ts
         sed -i "s/MEASUREMENT_ID: ''/MEASUREMENT_ID: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'/" ./src/environments/environment.ts

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ETUPRO_8E99F }}'
          channelId: live
          projectId: etupro-8e99f
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
