name: Validate and deploy master branch
'on':
  push:
    branches:
      - master
permissions:
  checks: write
  contents: read
jobs:
  build_and_test:
    uses: ./.github/workflows/validate.yml
    secrets: inherit

  firebase_deploy:
    needs: build_and_test
    uses: ./.github/workflows/firebase-deploy.yml
    secrets: inherit
