name: Validate PR
'on':
  pull_request:
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_test:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    uses: ./.github/workflows/validate.yml
    secrets: inherit
