name: Validate
'on':
  workflow_call:
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Replace values in environment.ts
        run: |
          sed -i "s@SUPABASE_URL@${{ secrets.SUPABASE_URL }}@" ./src/environments/environment.ts
          sed -i "s@SUPABASE_KEY@${{ secrets.SUPABASE_KEY }}@" ./src/environments/environment.ts

      - name: Install dependencies
        run: npm ci

      #      - name: Test project
      #        run: npm run test -- --watch=false --browsers=ChromeHeadlessCustom

      - name: Validate code quality
        run: npm run lint

      - name: Build project
        run: npm run build

  supabase_deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      PROJECT_ID: jhshraxeznmhpigjdzcq
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1

      - run: supabase projects list

      - run: supabase link --project-ref $PROJECT_ID

      - run: supabase storage ls
